apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
type: Opaque
data:
  # the original string is "password"
  admin.password: "JDJ5JDEwJFNjQmY0UHhadFV0aGtQR3dnZDNUQ2V1WnZRa1lqU3c5MmdFbXVsb0tJM08weTBRVndoS2Rp"
  admin.passwordMtime: "MjAyMS0wMi0yMVQyMDoxMjoyMVo="
